### ISSUE TITLE
Two exceptions originating from debugbar

### ISSUE THREAD

**Issue by eXpl0it3r** [scottbedard/oc-debugbar-plugin#25]
debugbar reports two expections cause by itself:

```
Cannot add AuthCollector to Laravel Debugbar: array_keys() expects parameter 1 to be array, null given
/..../plugins/bedard/debugbar/vendor/barryvdh/laravel-debugbar/src/LaravelDebugbar.php#454
```

```
array_keys() expects parameter 1 to be array, null given
/..../plugins/bedard/debugbar/vendor/barryvdh/laravel-debugbar/src/LaravelDebugbar.php#442
```

Might very well be related to the latest major update to OctoberCMS.

**Comment by zenzillo** [comment]
I had the same exceptions and I was able to fix it with [this code](https://github.com/barryvdh/laravel-debugbar/commit/d5c46b6a51b2773c6c8fbd149517a7719f4ff1f7) in the file: 

plugins/bedard/debugbar/barryvdh/laravel-debugbar/src/LaravelDebugbar.php

Now I get these errors and I don't know how to fix it...

`Cannot add AuthCollector to Laravel Debugbar: Class auth does not exist
/.../plugins/bedard/debugbar/vendor/barryvdh/laravel-debugbar/src/LaravelDebugbar.php#454`

`Class auth does not exist
/.../vendor/laravel/framework/src/Illuminate/Container/Container.php#752`

Can someone help? Has anyone seen this before?

I am using OctoberCMS 434, PHP 7.0 and Debugbar 2.0.0

**Comment by GinoPane** [comment]
Is this plugin abandoned?

**Comment by zenzillo** [comment]
I hope not! It's a great plugin, and I am still using it despite the errors.

**Comment by eXpl0it3r** [comment]
There's always the option to fix the issues yourself and send in a pull request. 😉

**Comment by scottbedard** [comment]
Sorry, I've been focused on other projects and haven't had time to dig into this. I like @eXpl0it3r's suggestion though, I'd happily accept a PR that addressed this issue :)

**Comment by osmanzeki** [comment]
Hey everyone!

I was able to fix this by making sure the plugin can make use of Laravel Debugbar's config files to ignore the missing `auth` class that is causing these exceptions.

Since you can't use **`php artisan publish`** in OctoberCMS you have to cheat a little bit by providing a own **`config.php`** where you copy the contents of Laravel Debugbar's **`debugbar.php`** options and write them into the namespace of the package in October at runtime. If you guys think this fix is good enough, I can make a PR. Let me know if you guys think I forgot anything. Here goes!

## Steps to follow to fix the issue

### Adding Laravel Debugbar's config file to the Plugin
1. Install the plugin as you usually do (composer or marketplace, up to you).

2. After the installation has completed, go to the plugin's `vendor` folder and copy the contents of Laravel Debugbar's config file. It can usually be found at this location : **`/plugins/bedard/debugbar/vendor/barryvdh/laravel-debugbar/config/debugbar.php`**.

3. Go to the root of this plugin's folder and create a new folder called `config`.

4. In this folder create a new file name `config.php`.

4. Paste the contents of the **`debugbar.php`** file into the new **`config.php`** file as is.

You should now have a file at the following location with the contents of the Laravel Debugbar's config file :

**`/plugins/bedard/debugbar/config/config.php`**

### Loading the config file at runtime

1. Edit **`/plugins/bedard/debugbar/Plugin.php`**.

2. Add this namespace at the top of the file :

```php
use Config;
```

3. Add these lines to your the `boot` function:

```php
// Setup configurations
$config = Config::get('bedard.debugbar::config');
if (!is_null($config)) {
    Config::set('debugbar', $config);
}
```
Your boot function should now look something like this :

```php
/**
 * Register service provider, Twig extensions, and alias facade.
 */
public function boot()
{
    // Service provider
    App::register('\Barryvdh\Debugbar\ServiceProvider');

    // Setup configurations
    $config = Config::get('bedard.debugbar::config');
    if (!is_null($config)) {
        Config::set('debugbar', $config);
    }

    // Register alias
    $alias = AliasLoader::getInstance();
    $alias->alias('Debugbar', '\Barryvdh\Debugbar\Facade');

    // Register middleware
    if (\Config::get('app.debugAjax', false)) {
        $this->app['Illuminate\Contracts\Http\Kernel']->pushMiddleware('\Bedard\Debugbar\Middleware\Debugbar');
    }

    Event::listen('cms.page.beforeDisplay', function ($controller, $url, $page) {
        // Only show for authenticated backend users
        if (!BackendAuth::check()) {
            Debugbar::disable();
        }

        // Twig extensions
        $twig = $controller->getTwig();
        if (!$twig->hasExtension(\Barryvdh\Debugbar\Twig\Extension\Debug::class)) {
            $twig->addExtension(new \Barryvdh\Debugbar\Twig\Extension\Debug($this->app));
            $twig->addExtension(new \Barryvdh\Debugbar\Twig\Extension\Stopwatch($this->app));
        }
    });
}
```

### Fixing the exceptions
Now that all this is done, you can go edit your local **`/plugins/bedard/debugbar/config/config.php`** and set the `auth` loading option that is causing the exceptions to `false` as follows :

```php

    // ...

    /*
    |--------------------------------------------------------------------------
    | DataCollectors
    |--------------------------------------------------------------------------
    |
    | Enable/disable DataCollectors
    |
     */

    'collectors' => [
        // ...
        'auth' => false, // Display Laravel authentication status
        // ...
    ],

    // ...

```

**Comment by tientamle** [comment]
Replace every steps above, for easier to fix it, just edit the file:

>  /plugins/bedard/debugbar/Plugin.php

and add the code below on top of the boot() function:

```
$config = \Config::get('debugbar', []);
if (isset($config['collectors']['auth'])) {
    $config['collectors']['auth'] = false;
    $config = \Config::set('debugbar', $config);
}
```

**Comment by empower-josh** [comment]
I was able to clean this up by using the suggestion provided by @tientamle along with editing:
.../plugins/bedard/debugbar/vendor/barryvdh/laravel-debugbar/config/debugbar.php
and setting collectors['auth'] to 'false'. (line 196 in my case).
