### ISSUE TITLE
how to install DebugBar  to  octobercms version 470?

### ISSUE THREAD

**Issue by lnmput** [scottbedard/oc-debugbar-plugin#46]
- OctoberCMS Build: 470
- DebugBar Plugin Version:  
- PHP Version: 7.4

### Description:
I can't find this plugin in the market

**Comment by daftspunk** [comment]
Hi @lnmput 

Apologies for the confusion around this plugin. The plugin is a developer tool and should only be installed to the local environment, this is why it does not appear on the market.

---

Here is some instructions for installation:

To install from [the repository](https://github.com/rainlab/debugbar-plugin), clone it into **plugins/rainlab/debugbar** and then run `composer update` from your project root in order to pull in the dependencies.

To install it with Composer, run `composer require rainlab/debugbar-plugin` from your project root.
