### ISSUE TITLE
problem update 1.0.3

### ISSUE THREAD

**Issue by ribsousa** [scottbedard/oc-debugbar-plugin#6]
syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$'
plugins/bedard/debugbar/vendor/barryvdh/laravel-debugbar/src/LaravelDebugbar.php line 372
TYPE

Undefined

EXCEPTION

Symfony\Component\Debug\Exception\FatalErrorException

```
            );
        }
    }

    if ($this->shouldCollect('gate', false)) {
        try {
            $gateCollector = $this->app->make(GateCollector::class);
            $this->addCollector($gateCollector);
        } catch (\Exception $e){
            // No Gate collector
        }
    }
```

**Comment by scottbedard** [comment]
This is happening because `::class` is not supported in PHP 5.4, it appears to have been fixed in https://github.com/barryvdh/laravel-debugbar/commit/3bf871f2d70e0412379613b2a52d03f5a3d6a75e

The easiest way for you to fix it on your end would be to start using PHP 5.5+, or wait for the next release of the debugbar dependency
